### ISSUE TITLE
Error handling in python code

### ISSUE THREAD

**Issue by Rangak** [EFForg/OpenWireless#106]
In general improve error handling in python code so failure is 
graceful from User's perspective. The variable or test being done should
indicate failure, but the page itself should not blow up as below : 

If WAN port of router is disconnected or otherwise IP connectivity is disrupted then 
going to dashboard page gives the following : 

Server Error: CalledProcessError: Command '['/usr/bin/wget', '-qO-', 'myexternalip.com/raw']' returned non-zero exit status 1, [' File "/www/cgi-bin/routerapi/dashboard", line 20, in <module>\n wan_ip = get_external_ip_address()\n', ' File "/www/cgi-bin/routerapi/ip_address_retriever.py", line 16, in get_external_ip_address\n return check_output(["/usr/bin/wget", "-qO-", "myexternalip.com/raw"])\n', ' File "/usr/lib/python2.7/subprocess.py", line 544, in check_output\n raise CalledProcessError(retcode, cmd, output=output)\n']

**Comment by mgumz** [comment]
i dont see the need to use subprocess("wget") at all if you are using python in the first place.
