### ISSUE TITLE
Pleas fix "/etc/rc.d" and other

### ISSUE THREAD

**Issue by build000** [EFForg/OpenWireless#216]
Pleas fix problem - delete another file to init process, like _luci_ and _polipo_ from <github-master>/etc/rc.d.
Its the same situations to _natpmp_ (/etc/config/natpmp) and _polipo_ (/etc/polipo), and _netperf-latest_ (/etc/xinetd.d/netserver)...
- 1) - how to fix this error ?:
- http://wklej.org/id/1430747/ 
- Can run /etc/init.d/sqm stop/start - no any changes.
- 2) - Other errors (tor):
- http://wklej.org/id/1430755/
- 3) - This is bug or not (iptables) ?:
- http://wklej.org/id/1430783/
- mdnsd remove (avahi-daemon not work properly).

My timezone is "Europe/Warsaw" (installing zoneinfo-{core, europe, simple} ).
My installed packages: http://wklej.org/id/1430811/

**Comment by Rangak** [comment]
Some cleanup was done as part of MVP-EA/alpha milestone. Revisit this and close this item for beta milestone.
