### ISSUE TITLE
WNDR3800CH (V1.0.0.51CH) won't take other firmware as easy

### ISSUE THREAD

**Issue by Veeshush** [EFForg/OpenWireless#224]
So I grabbed a refurbished WNDR3800 as mentioned on OpenWireless.org http://www.newegg.com/Product/Product.aspx?Item=N82E16833122523

Thing is, seems I received a WNDR3800CH, which ships with V1.0.0.51CH. The issue? See: https://forum.openwrt.org/viewtopic.php?id=49390

"Most likely it has a different firmware ID and to successfully flash another firmware to it, the other firmware should first be modfied to contain the required ID string. Then the OEM TFTPmode or upgrade will accept the new firmware as genuine/compatible."

I just wanted to let you guys know. Others who might grab the same refurbished link on Newegg might end up in the same boat as I am.

**Comment by polsVoice** [comment]
I just bought a WNDR3800CH, and I'm wondering what my options are. Is my best bet to just install OpenWRT on it?

**Comment by Rangak** [comment]
We are using close to stock openwrt now so the WNDR3800CH should be supported. You may need to enable it in the .config file in the openwrt submodule and build the image, though. We haven't released a built image for the CH. See the Readme for build instructions and look at the build script to figure out what to tweak. It takes a while to build but is quite simple to do.

**Comment by stefek99** [comment]
**AWRGH!**

There was not a single WNDR3800 available in Europe so I paid double price for shipping from the US...

Now I'm learning that I have WNDR3800CH model and I've essentially wasted couple of hours and I'm reading this thread.

_(not happy customer)_

**Comment by jsha** [comment]
Hi @stefek99! Sorry you had such a frustrating (and expensive) experience! Can I ask where you found the information that led you to buy a router to run this firmware? This project is no longer officially supported, so I want to make sure that's communicated clearly in as many places as possible.

**Comment by Mikaela** [comment]
> This project is no longer officially supported, so I want to make sure that's communicated clearly in as many places as possible.

That is not communicated on https://openwireless.org/ and https://github.com/EFForg/OpenWireless/issues/305 never got any project member or contributor to reply.

**Comment by jsha** [comment]
Thanks! I replied on #305. Can you tell me which page on openwireless.org led you to the firmware project? I'll make sure that page gets updated with details.

**Comment by stefek99** [comment]
@jsha - I had WNDR3800 on my shopping list / personal notes. Normally I'd buy the router straightway but whenever situation is like $20 for the product and another $20 for shipping / handling / customs / taxes my enthusiasm evaporates (I know, it's a virus).

I didn't realize that such a promising project can go offline :)

It was only later when I couldn't find the source when I realized that due to 0.1% market share the project is no more.

No harm done, I hope I'll be able to install regular DD-WRT or OpenWRT, I'm just having some troubles because of **CH** variant...

**Comment by jsha** [comment]
Glad to hear it, and I appreciate your enthusiasm!
