### ISSUE TITLE
Allow disabling the openwireless.org SSID bandwidth limit

### ISSUE THREAD

**Issue by davidstrauss** [EFForg/OpenWireless#241]
For some ISPs like Sonic.net, there's no point in specifying an overall cap because the customer has no limit. The GUI lets you set the limit to zero, but it's ambiguous whether this disables the limit or disables openwireless.org traffic.

**Comment by Rangak** [comment]
Fixed in https://github.com/EFForg/OpenWireless/commit/6bd6edf22a454767782f8e7ee624087b139d03da .
