### ISSUE TITLE
Check password lengths

### ISSUE THREAD

**Issue by c0ff3m4kr** [EFForg/OpenWireless#253]
Currently the passwords for the login and for the private wifi are only checked by Javascript. This is a bad practice in my opinion and those who want can set the password to one character or even set en empty password (at least for the login). I haven't tested what happens if the wifi password is smaller but I don't except something nice.
I've made a pull request (#252) as a suggestion to fix this.

Also I would like a function like `get_parameters(count)` in the `common` module which checks the request content and returns the parameters if the JSON message is valid and there are exactly the required length of `params` in it. I would appreciate to do this if you want.

**Comment by Rangak** [comment]
PR #252 has been merged. Second part of suggestion is a good idea. Please do submit a PR for that.

**Comment by jsha** [comment]
I think this doesn't meet any immediate needs. Please feel free to re-file or submit a PR if you would like to make this happen. Thanks!
