### ISSUE TITLE
software version should be a composite of OpenWireless version and underlying OpenWRT

### ISSUE THREAD

**Issue by beej** [EFForg/OpenWireless#266]
at https://openwireless.org/pipermail/user/2014-December/000049.html

ranga krishnan wrote:
>The Software Version does not change but the Software Version Date
does change. Thanks for noting this. 
>
>This happens because the Software Version is currently derived from 
the underlying  OpenWRT (CeroWRT) version only. We should fix this 
so it is a composite of OpenWireless version and the underlying.

**Comment by Rangak** [comment]
Fixed in https://github.com/EFForg/OpenWireless/commit/32588b9e6672e7da7132add5700bd4c6a5ec981c .
