### ISSUE TITLE
bandwidth limitation is being applied to private wi-fi and LAN

### ISSUE THREAD

**Issue by beej** [EFForg/OpenWireless#267]
the "Max bandwidth fraction" that is supposed to apply only to clients on the open wi-fi is apparently being applied to those on the private wi-fi and LAN networks.  changing percentage numbers affects my speedtest.net results commensurately.

**Comment by Rangak** [comment]
Not able to reproduce this. Needs further review.

**Comment by beej** [comment]
i can no longer reproduce this, either.
