### ISSUE TITLE
Set admin password

### ISSUE THREAD

**Issue by pleddy** [EFForg/OpenWireless#285]
Went on vacation for a week, and yet again, router reset by upgrade. This is getting REALLY irritating.

Now, when trying to set admin password.

Server Error: IOError: [Errno 2] No such file or directory: '/etc/auth/password', [' File "/www/cgi-bin/routerapi/login", line 32, in <module>\n jsonrpc_login()\n', ' File "/www/cgi-bin/routerapi/login", line 23, in jsonrpc_login\n tokens = a.authenticate(password, remote_address)\n', ' File "/www/cgi-bin/routerapi/auth.py", line 245, in authenticate\n if self.is_password(password):\n', ' File "/www/cgi-bin/routerapi/auth.py", line 158, in is_password\n with open(self.password_filename, \'r\') as f:\n']

**Comment by Rangak** [comment]
There as an upgrade a week ago and succeeding upgrades from now on should preserve your settings, including passwords. 

Regarding above error above: Were you following the initial install setup process  or were you trying to reset the admin password after completing a successful initial setup ?

While I look into this, you could you please try the fail safe method here 

https://github.com/EFForg/OpenWireless#failsafe-and-recovery

with the factory.img download from here:

https://openwireless.org/router/download

and let me know if you are successful ?

**Comment by pleddy** [comment]
OK, upgrade via fail-safe/tftp worked. Thanks! 

Looking forward to lasting settings now. :)
