### ISSUE TITLE
https://openwireless.org certificate not secure

### ISSUE THREAD

**Issue by RichardLitt** [EFForg/OpenWireless#302]
I don't know what OpenWireless is. I tried to go to https://openwireless.org to find out, and I got this:

<img width="668" alt="screenshot 2015-11-06 13 53 54" src="https://cloud.githubusercontent.com/assets/910753/11005831/2f3b8b74-848e-11e5-8214-fd74bae7de8f.png">

I don't know where to file this issue: the contribute link merely points back to this repository. 

Also, https://openwireless.org should be added to the repository description.

**Comment by Mikaela** [comment]
Same issue here and previously it was giving ERR_CONTENT_DECODING_FAILED. I think this is a problem with all those open WLANs with SSID openwireless.org and users cannot visit the site to read the rules.

<blockquote class="twitter-tweet" lang="fi"><p lang="en" dir="ltr">ERR_CONTENT_DECODING_FAILED here too and I wasn&#39;t able to find <a href="https://twitter.com/hashtag/openwireless?src=hash">#openwireless</a>.org Twitter, but found this instead. <a href="https://t.co/8Qr0SEJ1mO">https://t.co/8Qr0SEJ1mO</a></p>&mdash; Mikaela Suomalainen (@Inaneierase) <a href="https://twitter.com/Inaneierase/status/662601660221562880">6. marraskuuta 2015</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" lang="fi"><p lang="en" dir="ltr"><a href="https://twitter.com/EFF">@EFF</a> <a href="https://t.co/aDw4e5KGMQ">https://t.co/aDw4e5KGMQ</a> gives Content Encoding Error &quot;...uses an invalid or unsupported form of compression&quot;</p>&mdash; a k&#39;wala (@akwala) <a href="https://twitter.com/akwala/status/662403572387201024">5. marraskuuta 2015</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by Mikaela** [comment]
This seems to be fixed.

**Comment by RichardLitt** [comment]
Agreed.
