### ISSUE TITLE
Reason's for Open Wireless Movement: It's a climate action?

### ISSUE THREAD

**Issue by Mikaela** [EFForg/OpenWireless#309]
Hi again,

I came across these two articles and started wondering if Open Wireless Movement is a climate action if 4G uses more energy than cable/similar and while WLAN uses more energy than not having it, Open Wireless Movement makes it possible for other users to use the same connection.

* https://newrepublic.com/article/155993/can-internet-survive-climate-change
* https://solar.lowtechmagazine.com/2015/10/can-the-internet-run-on-renewable-energy.html ("*a solar-powered website, which means it sometimes goes offline*")

If yes, maybe it should be added on https://openwireless.org/ as an argument with some wording?

**Comment by jsha** [comment]
Thanks for the thought! I think we'd need a pretty compelling case that Open Wireless can decrease emissions before we would make that one of our arguments. As far as I can tell right now, there isn't enough data to make that point compellingly.
